//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interview.Models.Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientData
    {
        public int ID { get; set; }
        public string ClientName { get; set; }
        public int Sex { get; set; }
        public int City { get; set; }
        public string Address { get; set; }
        public string Budget { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
