//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interview.Models.Container
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeyValue
    {
        public int KeyID { get; set; }
        public string KeyName { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
